### ISSUE TITLE
Testes de unidade

### ISSUE THREAD

**Issue by kyriosdata** [CauaRebelo/cs-2019-01#11]
Veja aula-04

**Comment by CauaRebelo** [comment]
Ainda está WIP (Work in Progress) fiz alguns na branch teste, terminarei ao decorrer do possivel

**Comment by kyriosdata** [comment]
Olá Cauã,

fico contente que está trabalhando. Novamente, estou à disposição para me
dizer como posso contribuir com a sua formação, caso esteja tendo alguma
dificuldade.

Fábio

**Comment by kyriosdata** [comment]
Não encontrei os testes de unidade para o código em JavaScript?!!! Crie-os, até para facilitar a verificação das melhorias que devem ser introduzidas, tanto no código em JavaScript quanto no código em Java. Por exemplo, em **ex3.js**, linha 35, lê-se

```javascript
 const c = Math.trunc(dia + 2 * mes + 3 * (mes + 1) / 5 + ano + ano / 4 - ano / 100 + ano / 400);
```
que entendo não ser compatível com o algoritmo. Um teste pontual é suficiente para detectar que esta linha não implementa o algoritmo. Observe que _Math.floor_ deveria ser usado em cada divisão (real) acima, dado que no algoritmo estas divisões são inteiras. Ou seja, o algoritmo soma parcelas inteiras, enquanto a linha acima está somando parcelas reais e só então converte para um inteiro, o que resulta ser uma operação distinta daquela definida no algoritmo.

**Comment by CauaRebelo** [comment]
Resolvido

**Comment by kyriosdata** [comment]
Testes de unidade de Java estão no início apenas 4 dos métodos foram testados (são 21 ao todo).
